### ISSUE TITLE
Two different custom mode in single autolinktextview

### ISSUE THREAD

**Issue by sopharasum** [armcha/AutoLinkTextViewV2#5]
Hello,
Is it possible to have two different custom mode in a single text to display on AutoLinkTextView ?
For example: Android is a operating system.
I want to custom on wording "Android" and "system" and display on AutoLinkTextView.

Thanks advanced for your reply.

Have a good day.

**Comment by enofeb** [comment]
I tried many times but I think it is not possible in this library. I have created mention mode for my mentions and after I needed to add hashtag custom mode but library doesn't allow it. It allows to use just one of them.

**Comment by armcha** [comment]
Please check version 3.0.0
