### ISSUE TITLE
URL first letter not highlighted 

### ISSUE THREAD

**Issue by RohiniRaman31** [armcha/AutoLinkTextViewV2#7]
if the url is the starting at the first word in the textview the first letter in the url not highlighted,this library has this [commit](https://github.com/armcha/AutoLinkTextViewV2/commit/54d6b240dbfdaf21068b691cc896111b78d26c1b) for this issue but the library doesn't have this changes version 2.1.1

**Comment by BilalSiddiqui** [comment]
Having same problem.....

**Comment by enofeb** [comment]
I have same problem either

**Comment by BilalSiddiqui** [comment]
Try this:
https://github.com/BilalSiddiqui/AutoLinkTextViewV2

First letter + multiple custom modes.

**Comment by armcha** [comment]
A new release is coming )

**Comment by armcha** [comment]
Please use version 3.0.0

**Comment by omeraslam-citrusbits** [comment]
@armcha I guess issue is not fixed for all cases. I am still facing the issue. 

e.g if text is: This is a Link google.com
In above first g will not be highlighted.

Issue seems to fix if I don't increment `startPoint += 1`. Can u verify?

Also i am not sure why you are incrementing startPoint in case of url.
